server:
  port: 8087
  servlet:
    context-path: /api

spring:
  application:
    name: SkillService

  kafka:
    bootstrap-servers: broker:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: skill.verified:com.freelancex.skillservice.dtos.SkillVerifiedEvent

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: postgresql

  datasource:
    url: jdbc:postgresql://postgres:5432/skill_service
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com: INFO
    org.apache.kafka: ERROR

springdoc:
  swagger-ui:
    path: /skill/swagger-ui.html
  api-docs:
    path: /skill/v3/api-docs

kafka:
  topics:
    skill-verified: skill.verified
